### ISSUE TITLE
Client assembles URL incorrectly under Windows

### ISSUE THREAD

**Issue by nlessmann** [rewonc/pastalog#1]
The client (Log class) does not work under Windows because it assembles the URL using `os.path.join()`, which is intended for filesystem paths and not URLs:

```
self.url = os.path.join(url, 'data')
```

Under Windows, the path fragments are concatenated with a backslash, so that the URL turns out as "http://localhost:8120\data".

**Comment by rewonc** [comment]
Thanks for the tip. I've switched to using urlparse in #2 .

Can you confirm that the following code works as expected in your environment?

``` python
from urlparse import urljoin
url = urljoin('localhost:8120', 'data')
```

**Comment by nlessmann** [comment]
Yes, then it works. Thanks!
