### ISSUE TITLE
Install not recognizing npm and node

### ISSUE THREAD

**Issue by linamnt** [rewonc/pastalog#17]
When installing, it doesn't seem to recognize that I have node and npm? I have restarted and tried again and the same results below. Sorry if this isn't really a pastalog problem, but rather on my end, I'm just not sure what to do.

```
$ pastalog --install
Please install npm and node.

Li@Talon ~/pastalog (master)
$ npm -v
3.10.5

Li@Talon ~/pastalog (master)
$ node -v
v6.3.1

```

**Comment by grep-rohan** [comment]
@linamnt Did you find the solution?
