### ISSUE TITLE
Update pip package

### ISSUE THREAD

**Issue by varunagrawal** [rewonc/pastalog#20]
If I install Pastalog directly from pip, I get the missing parenthesis error of Python 2. After looking at the code, this is not the case and the code is Python 3 compatible.

Would really appreciate it if the pip package was updated so we can enjoy pastalog in all its glory.

**Comment by ghost** [comment]
+1 - same missery :)

**Comment by varunagrawal** [comment]
Update -  I recommend using Facebook's Visdom.
