### ISSUE TITLE
Server crashes when trying to rename not-existing database.json

### ISSUE THREAD

**Issue by nlessmann** [rewonc/pastalog#3]
The server always crashes on Windows if there is no "database.json" file. The error message is this:

> D:\Software\pastalog\build\server.js:7357
>                   throw renameError;
>                   ^
> 
> Error: ENOENT: no such file or directory, rename 'D:\Software\pastalog\database.json' -> 'D:\Software\pastalog\database.json.~BACKUP'
>     at Error (native)

Apparently it's trying to rename the file, but this fails if there is no file to rename. After I manually added an empty file "database.json" everything works fine.

**Comment by rewonc** [comment]
Interesting. I catch this error on OSX, but I guess it throws a slightly different code in Windows. Will investigate. Thanks for being the cross-platform guinea pig!

**Comment by nlessmann** [comment]
I get for `renameError.errno` a value of -4058. Maybe it's better to test if `renameError.code == 'ENOENT`? That works for me at least.

**Comment by rewonc** [comment]
That works for OSX as well, so I've made that change in #2. Thanks!
