### ISSUE TITLE
Torch interface

### ISSUE THREAD

**Issue by Kaixhin** [rewonc/pastalog#4]
I made a simple Torch interface [here](https://github.com/Kaixhin/torch-pastalog) - should simplify the process for people who want to use pastalog with Torch. You may want to add in your readme somewhere?

**Comment by rewonc** [comment]
Awesome! Looks great. Yes, definitely send a PR.

**Comment by rewonc** [comment]
Or I'll add it in later when I get back to my computer

**Comment by rewonc** [comment]
Added.
