### ISSUE TITLE
Browser UI keeps downloading the whole data in a loop

### ISSUE THREAD

**Issue by apaszke** [rewonc/pastalog#9]
<img width="1437" alt="screen shot 2016-04-16 at 12 04 49" src="https://cloud.githubusercontent.com/assets/4583066/14580387/8fe54b60-03cb-11e6-8f7f-f07289077660.png">
When you accumulate some training data, it becomes unusable. My connection with a remote server is completely clogged with repeated data transfers. It downloads **everything every time**, but since pastalog already uses web sockets, it could only push out diffs.

Also, I can't delete the old series anymore, so I can't stop it anyhow :confused:

**Comment by rewonc** [comment]
Hi Adam,

Can you provide some more context about how you're using pastalog? E.g. the
calls you're making to the server on that network graph, and the amount of
data you have stored?

Additionally when does the delete fail?

Currently, updates are sent as diffs and you shouldn't see obscene latency.
If you delete something, it does send over all the data.

Rewon

**Comment by rewonc** [comment]
If you have more details, let me know and I'll reopen the issue.
